print("*"*6,"Kredit Keaktifan Mahasiswa","*"*6)
print("(Student Activities Credit)")
print("1. Menambahkan Kegiatan")
print("2. Menampilkan Jumlah Poin")
print("3. Keluar")
print("----------------------------")
pilihan = int(input("Silahkan masukkan pilihan yang Anda : "))
if pilihan == 1:
    input("Nama Kegiatan: ")
    input("Tanggal Kegiatan: ")
    print("Pilihan Kategori Kegiatan: ")
    print(" - Prestasi")
    print(" - Organisasi")
    print(" - Kepanitiaan")
    print(" - Rekognisi")
    pilihan = input("Masukkan Kategori Kegiatan :")
    print()
    print("Kegiatan berhasil ditambahkan.")
elif pilihan == 2:
    print()
    print("----------------------------")
    print("Nama Kegiatan    Tanggal             Kategori       Poin")
    input("1.HMTI 2022      tahun 2022-2023     organisasi      10")
    print("2.iaa 2022       24 mei 2022         kepanitiaan      5")
    print("3.FAITH Petra    30 juli 2022        prestasi        30")
    print("4.Webinar UI/UX  2 - 05 - 2022       rekognisi        2")
    print("5. OKA 2022      22 AGUSTUS 2022     kepanitiaan      5")
    print("JUMLAH POIN TOTAK POIN       :   52")
elif pilihan == 3:
    print("Sistem Berhenti...")
